function filename = name(p,m,gain,BERtarget)
if strcmp(p.equalization,'none')
    filename = sprintf(['%sGbd/%dPAM/PAM_BER_TxBW=%dGHz_RxBW=%dGHz%s_%s_lev=%s_'...
        'amp=%s_G=%sdB_eq=%s_BER=%.2e_L=%dkm.mat'], ...
        num2str(p.RsGbd),m,p.ModBWGHz, p.RecBWGHz, num2str(p.fc), p.modulator, p.levels, ...
        p.amp,num2str(gain),p.equalization,BERtarget,p.Lkm);    
else
    filename = sprintf(['%sGbd/%dPAM/PAM_BER_TxBW=%dGHz_RxBW=%dGHz_%s_lev=%s_'...
        'amp=%s_G=%sdB_eq=%s_BER=%.2e_L=%dkm.mat'], ...
        num2str(p.RsGbd),m,p.ModBWGHz, p.RecBWGHz, p.modulator, p.levels, ...
        p.amp,num2str(gain),p.equalization,BERtarget,p.Lkm);
end
    strrep(filename,' ','-');       % replace spaces
end